class GameState:
    """Tracks the state of a single round of Spot the Difference.

    Manages found regions, mistake count, and win/loss conditions.
    """

    def __init__(self):
        """Initialise a default game state with no regions and zero counts."""
        self.regions = []
        self.mistakes = 0
        self.max_mistakes = 3
        self.found_count = 0
        self.total_differences = 5

    def new_round(self, regions: list):
        """Reset the game state for a new round.

        Args:
            regions: List of region dicts generated by ImageProcessor.get_regions().
        """
        self.regions = regions
        self.mistakes = 0
        self.max_mistakes = 3
        self.found_count = 0
        self.total_differences = 5

    def check_click(self, x: int, y: int) -> str:
        """Evaluate a click against all unfound difference regions.

        Args:
            x: The x coordinate in original image space.
            y: The y coordinate in original image space.

        Returns:
            'hit'           -- click landed on an unfound region.
            'already_found' -- click landed on a previously found region.
            'miss'          -- click did not land on any region.
            'locked'        -- max mistakes already reached; click ignored.
        """
        if self.mistakes >= self.max_mistakes:
            return 'locked'

        for region in self.regions:
            if (region['x'] <= x <= region['x'] + region['w']
            and region['y'] <= y <= region['y'] + region['h']):
                if region['found']:
                    return 'already_found'

                region['found'] = True
                self.found_count += 1
                return 'hit'

        self.mistakes += 1
        return 'miss'

    def get_found_regions(self) -> list:
        """Return a list of all regions that have been found."""
        return [r for r in self.regions if r['found']]

    def get_unfound_regions(self) -> list:
        """Return a list of all regions that have not yet been found."""
        return [r for r in self.regions if not r['found']]

    def is_game_over(self) -> bool:
        """Return True if the game has ended, either by completion or too many mistakes."""
        return (self.mistakes >= self.max_mistakes
                or
                self.found_count == self.total_differences)

    def get_remaining(self) -> int:
        """Return the number of differences still to be found."""
        return self.total_differences - self.found_count

    def get_mistakes(self) -> int:
        """Return the current number of mistakes made."""
        return self.mistakes

    def is_complete(self) -> bool:
        """Return True if all differences have been found."""
        return self.found_count == self.total_differences

    def is_locked(self) -> bool:
        """Return True if the maximum number of mistakes has been reached."""
        return self.mistakes >= self.max_mistakes
    